### ISSUE TITLE
Додати  сортування

### ISSUE THREAD

**Issue by prihodkoserge** [don585/TPPS_EuroDiffusion#1]
https://github.com/don585/TPPS_EuroDiffusion/blob/0c1e2699ed9afcd56181d53853afbd899ba4e16b/EuroDiffusion/EuroDiffusion.cs#L95
У вимогах до завдання вказано, що в тому випадку, коли отримано однакову кількість днів розповсюдження монет, то тоді країни повинні бути відсортовані за алфавітом

**Comment by don585** [comment]
Виправлено
