### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by prihodkoserge** [don585/TPPS_EuroDiffusion#2]
https://github.com/don585/TPPS_EuroDiffusion/blob/0c1e2699ed9afcd56181d53853afbd899ba4e16b/EuroDiffusion/EuroDiffusion.cs#L32
Чому методи, що виконують коректність введених даних, не реалізовані за допомогою класу Exception?

**Comment by don585** [comment]
Виправлено. Обробка помилок виконується за допомогою класу Exception
