### ISSUE TITLE
Constants inside the class namespace

### ISSUE THREAD

**Issue by IanaKhitsko** [don585/TPPS_EuroDiffusion#4]
https://github.com/don585/TPPS_EuroDiffusion/blob/78593a4dfc01b1c3a1eb8cef0ccdd433868bbffa/EuroDiffusion/CoinDistribution.cs#L11-L18

Do you really need all these consts inside the class ?

**Comment by don585** [comment]
In previous issue I explain why all these const variables are inside the class.
