### ISSUE TITLE
Const inside the class 

### ISSUE THREAD

**Issue by IanaKhitsko** [don585/TPPS_EuroDiffusion#5]
https://github.com/don585/TPPS_EuroDiffusion/blob/78593a4dfc01b1c3a1eb8cef0ccdd433868bbffa/EuroDiffusion/EuroDiffusion.cs#L11-L16

Can we move consts outside  the class ?

**Comment by don585** [comment]
No. The const keyword is used to modify a declaration of a local variable. So local variables can exist only within a class, this means that I cannot have a global const.
